const SET_HOTELS = 'SET_HOTELS';
const SET_HOTELS_PRICE = 'SET_HOTELS_PRICE';
const SET_HOTELS_DETAILS = 'SET_HOTELS_DETAILS';

export {
    SET_HOTELS,
    SET_HOTELS_PRICE,
    SET_HOTELS_DETAILS,
}